name: sennit
description: Send Anything Anywhere

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  place_picker: ^0.9.9
  flutter_google_places: ^0.2.3
  # flutter_polyline_points: ^0.1.0
  google_maps_flutter: ^0.5.21+15
  google_map_polyline: ^0.2.0+1
  geolocator: ^3.0.1
  geocoder: ^0.2.1
  sqflite:
  path:
  location: ^2.3.5
  page_view_indicators: ^1.3.0
  auto_size_text: ^2.1.0
  carousel_slider: ^1.3.1
  pin_code_fields: ^2.3.0+1
  flutter_rating: ^0.0.2
  password: ^1.0.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  flappy_search_bar: ^1.4.1




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/cocologo.jpeg
    - assets/images/body_cream.jpeg
    - assets/images/body_lotion.jpg
    - assets/images/body_wash.jpeg
    - assets/images/glcerin_soaps.jpeg
    - assets/images/lip_butter.jpeg
    - assets/images/logo.png
    - assets/images/delivery.png
    - assets/secret.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ArchivoNarrow
      fonts:
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-Regular.ttf
          weight: 400
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-Medium.ttf
          weight: 500
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-SemiBold.ttf
          weight: 600
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-Bold.ttf
          weight: 700
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
