name: sennit
description: Send Anything Anywhere

version: 2.3.3+53

environment:
  sdk: ">=2.7.0 <3.0.0"

# dependency_overrides:
#   firebase_core: 0.4.4
#   intl: ^0.16.0
#   flutter_svg: ^0.17.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: #^0.1.2
  font_awesome_flutter: #^8.5.0
  google_map_location_picker: #^3.2.1
  flutter_mapbox_navigation: #^0.0.10
  flutter_google_places: #^0.2.3
  google_maps_flutter: #^0.5.21+15
  google_map_polyline: #^0.2.0+1
  maps_launcher: #^1.2.0
  geolocator: #^5.2.1
  geocoder: #^0.2.1
  sqflite: #^1.2.1
  path: #^1.6.4
  location: #^2.3.5
  # background_location: # 0.0.11
  page_view_indicators: #^1.3.0
  auto_size_text: #^2.1.0
  pin_code_fields: #^2.3.0+1
  flutter_rating: #^0.0.2
  password: #^1.0.0
  firebase_core: #^0.4.0+9
  firebase_analytics: #^5.0.2
  firebase_storage:
  cloud_firestore: #^0.13.0+1
  firebase_auth: #0.15.4
  firebase_messaging: #^6.0.12
  flappy_search_bar: #^1.4.1
  bot_toast: #^2.2.0
  argon_buttons_flutter: #^1.0.2
  flutter_email_sender: #^2.2.2
  solid_bottom_sheet: #^0.1.9
  mailer: #^3.0.4
  flutter_speed_dial: #^1.2.5
  random_string: #^2.0.1
  http: #^0.12.0+4
  flutter_local_notifications: #^1.4.3
  rave_flutter: #^0.0.9-alpha+1
  carousel_slider: #^1.4.1
  flutter_full_pdf_viewer: #^1.0.6
  path_provider: #^1.6.5
  open_appstore: #^1.0.2
  shortid: #^0.1.1
  rxdart: #^0.22.2
  get_it: #^3.1.0
  connectivity: #^0.4.8+6
  shared_preferences: #'0.5.7+3'
  geotools:
  # permission_handler:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/right.png
    - assets/images/logo.png
    - assets/images/delivery.png
    - assets/secret.json
    - assets/docs/privacy_policy.pdf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ArchivoNarrow
      fonts:
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-Regular.ttf
          weight: 400
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-Medium.ttf
          weight: 500
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-SemiBold.ttf
          weight: 600
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-Bold.ttf
          weight: 700
        - asset: fonts/ArchivoNarrow/ArchivoNarrow-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
